version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: "mongodb://db:27017"
    depends_on:
      - db
  db:
    image: mongo:6.0.5
    volumes:
      - db-data:/data/db
volumes:
  db-data:
